/**
 * Provider Capability Registry — WORKER COPY (Issue #117)
 *
 * KEEP IN SYNC with src/lib/provider-capabilities.ts (canonical).
 * The worker Docker image excludes src/, so this copy is required —
 * same pattern as lib/crypto.ts.
 *
 * A unit test (tests/unit/lib/provider-capabilities.test.ts) asserts both
 * files export identical data to enforce single source of truth.
 *
 * DO NOT edit this file without updating src/lib/provider-capabilities.ts too.
 */

export type PlatformKey =
  | 'telegram'
  | 'instagram'
  | 'linkedin'
  | 'rubika'
  | 'bale'
  | 'eitaa'

export interface ProviderCapability {
  supportsText: boolean
  supportsImage: boolean
  supportsVideo: boolean
  maxTextLength: number
  maxCaptionLength: number
  requiresMedia: boolean
  maxMediaCount: number
  maxHashtags: number | null
  label: string
}

export const PROVIDER_CAPABILITIES: Record<PlatformKey, ProviderCapability> = {
  telegram: {
    supportsText: true,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 4096,
    maxCaptionLength: 1024,
    requiresMedia: false,
    maxMediaCount: 10,
    maxHashtags: null,
    label: 'تلگرام',
  },
  instagram: {
    supportsText: false,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 2200,
    maxCaptionLength: 2200,
    requiresMedia: true,
    maxMediaCount: 10,
    maxHashtags: 30,
    label: 'اینستاگرام',
  },
  linkedin: {
    supportsText: true,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 3000,
    maxCaptionLength: 3000,
    requiresMedia: false,
    maxMediaCount: 9,
    maxHashtags: null,
    label: 'لینکدین',
  },
  rubika: {
    supportsText: true,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 4096,
    maxCaptionLength: 1024,
    requiresMedia: false,
    maxMediaCount: 10,
    maxHashtags: null,
    label: 'روبیکا',
  },
  bale: {
    supportsText: true,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 4096,
    maxCaptionLength: 1024,
    requiresMedia: false,
    maxMediaCount: 10,
    maxHashtags: null,
    label: 'بله',
  },
  eitaa: {
    supportsText: true,
    supportsImage: true,
    supportsVideo: true,
    maxTextLength: 4096,
    maxCaptionLength: 1024,
    requiresMedia: false,
    maxMediaCount: 10,
    maxHashtags: null,
    label: 'ایتا',
  },
}

export function getCapabilities(platform: string): ProviderCapability {
  return (
    PROVIDER_CAPABILITIES[platform as PlatformKey] ?? PROVIDER_CAPABILITIES.telegram
  )
}

export interface CapabilityViolation {
  code: string
  message: string
  platform: string
}

export function validateAgainstCapabilities(
  platform: string,
  content: { body: string | null; hashtags: string | null; mediaCount: number }
): CapabilityViolation[] {
  const cap = getCapabilities(platform)
  const issues: CapabilityViolation[] = []
  const text = content.body ?? ''
  const isMediaPost = content.mediaCount > 0
  const effectiveLimit = isMediaPost ? cap.maxCaptionLength : cap.maxTextLength

  if (text.length > effectiveLimit) {
    issues.push({
      code: 'caption_too_long',
      message: `متن نباید از ${effectiveLimit} کاراکتر بیشتر باشد (پلتفرم: ${cap.label}).`,
      platform,
    })
  }

  if (cap.requiresMedia && content.mediaCount === 0) {
    issues.push({
      code: 'media_missing',
      message: `${cap.label} به حداقل یک تصویر یا ویدیو نیاز دارد.`,
      platform,
    })
  }

  if (cap.maxHashtags !== null) {
    const hashtagCount = (content.hashtags?.match(/#/g) || []).length
    if (hashtagCount > cap.maxHashtags) {
      issues.push({
        code: 'too_many_hashtags',
        message: `${cap.label} حداکثر ${cap.maxHashtags} هشتگ مجاز می‌کند.`,
        platform,
      })
    }
  }

  if (content.mediaCount > cap.maxMediaCount) {
    issues.push({
      code: 'too_many_media',
      message: `${cap.label} حداکثر ${cap.maxMediaCount} رسانه در هر پست مجاز می‌کند.`,
      platform,
    })
  }

  return issues
}
